version: 2
updates:
  - package-ecosystem: "npm" # Specify the package ecosystem, e.g., npm, yarn, etc.
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly" # Schedule interval for updates
