openapi: 3.0.0
info:
  title: OpenAPI Workspace GitHub
  description: Introducing OpenAPI into a Vue App SSR with Vite using Composition API built-in feature of Vue 3, TS, Tailwind CSS v4.0.3, and Supabase for Authentication and Storage.
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local server
paths:
  /auth/signup:
    post:
      summary: Sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                username:
                  type: string
              required:
                - email
                - password
                - username
      responses:
        "200":
          description: User signed up successfully
        "400":
          description: Invalid input
  /auth/signin:
    post:
      summary: Sign in an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: User signed in successfully
        "400":
          description: Invalid input
  /auth/signout:
    post:
      summary: Sign out the current user
      responses:
        "200":
          description: User signed out successfully
  /profile:
    get:
      summary: Get user profile
      responses:
        "200":
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  avatarUrl:
                    type: string
        "401":
          description: Unauthorized
    put:
      summary: Update user profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                avatarUrl:
                  type: string
              required:
                - username
      responses:
        "200":
          description: User profile updated successfully
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
