/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Workspace GitHub
 * Introducing OpenAPI into a Vue App SSR with Vite using Composition API built-in feature of Vue 3, TS, Tailwind CSS v4.0.3, and Supabase for Authentication and Storage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

